const dependencyMap = {
  "businessUnits": {
    "Robinsons Supermarket Region 1 & 3": [
      "RS TOWNVILLE CABANATUAN",
      "RS RP ILOCOS NORTE",
      "RS TALAVERA SQUARE ILAGAN",
      "RS RP SANTIAGO",
      "RS XENTRO MALL VIGAN",
      "RS ALICIA ISABELA",
      "RS RP TUGUEGARAO",
      "RS TOWNVILLE GAPAN NUEVA ECIJA",
      "RS SAN MIGUEL BULACAN",
      "RS NEPOMALL ANGELES",
      "RS IBA TOWN CENTER ZAMBALES",
      "RS DOLORES SAN FERNANDO",
      "RS GUAGUA TOWNCENTER",
      "RS XEVERA MABALACAT",
      "RS GCC MEXICO PAMPANGA",
      "RS HERMOSA BATAAN",
      "RS STARMILLS PAMPANGA",
      "RS RP ANGELES",
      "RS RP TARLAC",
      "RS RP PANGASINAN",
      "RS PORTA VAGA MALL BAGUIO",
      "RS SAN CARLOS TC PANGASINAN",
      "RS RP LA UNION",
      "RS METROTOWN TARLAC",
      "RS TANEDO TARLAC",
      "RS NEPOMALL DAGUPAN",
      "RS METROPLAZA QUIRINO CALOOCAN",
      "RS KAI MALL ZABARTE CALOOCAN",
      "RS TOWNVILLE PULILAN",
      "RS BALAGTAS TOWNCENTER",
      "RS TOWNVILLE MEYCUAYAN",
      "RS RP MALOLOS",
      "RS GROTTO SHOP N RIDE BULACAN",
      "RS RP NOVALICHES",
      "EL PASEO",
      "RS RP ERMITA",
      "RS TUTUBAN CENTERMALL",
      "RS CITI SQUARE MALABON",
      "RS RP OTIS",
      "RS VICTORY MALL CALOOCAN",
      "RS RP MAGNOLIA",
      "RS TOWN MALL MALABON",
      "RS FEDERAL BAY GARDEN PASAY",
      "RS CIRCLE CONGRESSIONAL",
      "RS BERKELEY COMMONWEALTH",
      "RS VICTORIA TOWER TIMOG",
      "RS RMR SQUARE TANDANG SORA",
      "RS Z SQUARE BANAWE",
      "RS B HIVE MALL VALENZUELA",
      "RS RIOKING DON ANTONIO",
      "RS DONA CARMEN FAIRVEW",
      "RS TOWNVILLE REGALADO FAIRVIEW",
      "RS CLOVERLEAF MALL BALINTAWAK",
      "RS HAPPY GO MALL VALENZUELA",
      "RS RP CEBU",
      "RS BANILAD CEBU",
      "RS TALISAY CEBU",
      "RS PUEBLO VERDE MACTAN",
      "RS SOUTH TOWN CENTER TABUNOK",
      "RS TALAMBAN TIME SQUARE CEBU",
      "RS ISLAND CENTRAL MACTAN",
      "RS BASELINE CENTER CEBU",
      "RS BELMONT ONE MINGLANILLA",
      "RS CASA MIRA GUADALUPE",
      "RS BAY MALL LILOAN CEBU",
      "RS FILINVEST SHOPPES CEBU",
      "RP DUMAGUETE",
      "RP TACLOBAN",
      "PERDICES",
      "ORMOC CENTRUM",
      "RP ROXAS",
      "CITYMALL ROXAS",
      "RP NORTH TACLOBAN",
      "RP ORMOC"
    ],

    "Robinsons Supermarket Region 2": [
      "RS MONTALBAN TOWNCENTER",
      "RS EASTWOOD TECHNOPLAZA II",
      "RS GRACELAND PLAZA MARIKINA",
      "RS KARANGALAN PASIG",
      "RS RP ANTIPOLO",
      "RS RP METROEAST",
      "RS ROBINSONS GALLERIA QC",
      "RS CALIFORNIA MANDALUYONG",
      "RS MERCEDES PASIG",
      "RS GATEWAY CUBAO",
      "RS ACACIA ESCALADES PASIG",
      "RS RP CAINTA",
      "RS CHOICE MARKET ORTIGAS PASIG",
      "RS TOWNVILLE PARANAQUE",
      "RS WOODSVILLE MERVILLE",
      "RS MADISON GALLERIES MUNTINLUPA",
      "RS RP LAS PINAS",
      "RS SOUTHPARK MALL ALABANG",
      "RS ONE AYALA MAKATI",
      "RS CENTRO PACITA",
      "RS CALAPAN TOWNCENTER MALL",
      "RS XENTRO MALL LEMERY BATANGAS",
      "RS LIPA TOWN CENTER",
      "RS LIMA EXCHANGE BATANGAS",
      "RS SAN JOSE OCCIDENTAL MINDORO",
      "RS RP LIPA",
      "RS ALBAY 738 LEGAZPI",
      "RS TARGET MALL STA ROSA",
      "RS EMALL NAGA",
      "RS SUMMIT RIDGE TAGAYTAY",
      "RS TOWNVILLE NUVALI STA ROSA",
      "RS PREMIER PLAZA SILANG",
      "RS TWIN LAKES VILLAGE BATANGAS",
      "RS RP NAGA",
      "RS RP IMUS",
      "RS TOWNVILLE ARVO DASMARINAS",
      "RS TOWNVILLE BUHAY NA TUBIG",
      "RS RP GENERAL TRIAS",
      "RS MAIN SQUARE MOLINO",
      "RS KINGHOME BUCANDALA IMUS",
      "RS RP DASMARINAS",
      "RS RP LOS BANOS",
      "RS RP PALAWAN",
      "RS IMALL CANLUBANG",
      "RS CENTRO MALL CABUYAO",
      "RS SOUTHWOODS MALL LAGUNA",
      "RS RP GALLERIA SOUTH SAN PEDRO",
      "RS METRO CENTRAL MALL STA CRUZ",
      "RS RP STA ROSA"
    ],

    "Robinsons Supermarket Region 4": [
      "RS C3 MALL PAGADIAN",
      "RS GEEGEE MALL OZAMIZ",
      "RS RP BUTUAN",
      "RS LIMKETKAI MALL CDO",
      "RS RP ILIGAN",
      "RS OROQUIETA MISAMIS OCC",
      "RS RP CAGAYAN DE ORO",
      "RS RP PAGADIAN",
      "RS CYBERGATE DAVAO",
      "RS TOWNVILLE ABREEZA DAVAO",
      "RS GUSA CAGAYAN DE ORO",
      "RS LAVINA PARK VALENCIA",
      "RS RP TAGUM",
      "RS AL NOR MALL COTABATO",
      "RS RP VALENCIA",
      "RS RP GENERAL SANTOS",
      "RS SOLIN MALL POLOMOLOK",
      "RS TANDAG SURIGAO DEL SUR",
      "RS STA LUCIA MALL DAVAO",
      "RS CALUMPANG",
      "RS RP BACOLOD",
      "RS RP ILOILO",
      "RS BACOLOD TRIANGLE",
      "RS GT PARK PLACE MOLO",
      "RS RP ANTIQUE",
      "RS RP JARO ILOILO",
      "RS VILLAMONTE BACOLOD",
      "RS OPEN MARKET MANSILINGAN",
      "RS RP PAVIA ILOILO"
    ],

    "Robinsons Easymart": [
      "RE POBLACION EAST MUNOZ NE",
      "RE SUCLAYIN BALER AURORA",
      "RE GUIMBA NUEVA ECIJA",
      "RE CONCEPCION TARLAC",
      "RE SAN SEBASTIAN TARLAC",
      "RE LIGTASAN TARLAC",
      "RE SAN VICENTE TARLAC",
      "RE MARKET CITY MALL TARLAC",
      "RE CITY CENTER MATATALAIB",
      "RE RODLEA BLDG BAMBAN TARLAC",
      "RE STARHOMES TARLAC",
      "RE RIZAL NUEVA ECIJA",
      "RE MAPANDAN PANGASINAN",
      "RE GENERAL AVENUE QC",
      "RE KAPITAN PEPE CABANATUAN CTY",
      "RE BANGAD CABANATUAN",
      "RE CANDON CITY ILOCOS SUR",
      "RE NEPO MALL",
      "RE LINGSAT LA UNION",
      "RE FRIENDSHIP ANGELES",
      "RE FIL AM ANGELES",
      "RE CUTCUT ANGELES PAMPANGA",
      "RE PULUNG CACUTUD PAMPANGA",
      "RE PIO PORAC PAMPANGA",
      "RE EPL PORAC PAMPANGA",
      "RE CROWN B BLDG STO TOMAS",
      "RE CAPITOL BLVD PAMPANGA",
      "RE GLOBAL PLAZA SAN SIMON",
      "RE SOLANA BACOLOR PAMPANGA",
      "RE MAGALANG PAMPANGA",
      "RE PANDAN TABUN ANGELES",
      "RE CGS BLDG CALUMPIT BULACAN",
      "RE VICTORY STATION OLONGAPO",
      "RE ORANI BATAAN",
      "RE APALIT PAMPANGA",
      "RE CASTILLEJOS ZAMBALES",
      "RE MALABANIAS",
      "RE ARBORTOWNE PLAZA VALENZUELA",
      "RE VALENZUELA TOWN CENTER",
      "RE SAVERS MART ROOSEVELT",
      "RE BLOCK ONE ROOSEVELT",
      "RE M NAVAL NAVOTAS",
      "RE CASA ANSELMO MALOLOS",
      "RE HAGONOY BULACAN",
      "RE HPLCENTER GUIGUINTO BULACAN",
      "RE SAN JOSE DEL MONTE BULACAN",
      "RE SKYLINE DRIVE SJDM BULACAN",
      "RE SAN MIGUEL BULACAN",
      "RE GIL CARLOS BALIUAG",
      "RE ESGUERRA PULILAN",
      "RE SHOP N RIDE NOVALICHES",
      "RE SUSANO COMPLEX NOVALICHES",
      "RE HOLIDAY ISLAND BAGONGSILANG",
      "RE METROPLAZA BAGONG SILANG",
      "RE SACRED HEART CALOOCAN",
      "RE FAIRVIEW CENTER MALL",
      "RE FILINVEST BATASAN HILLS",
      "RE SUNBEST BUILDING LAGRO",
      "RE LAGRO QUIRINO HI-WAY",
      "RE DAHLIA AVENUE QUEZON CITY",
      "RE OLD SAUYO QUEZON CITY",
      "RE THE EMERALD COURT PROJECT 6",
      "RE CULIAT TOWN CENTER",
      "RE MIRA NILA PASONG TAMO QC",
      "RE THE PLAZA",
      "RE E. RODRIGUEZ SR. QC",
      "RE LOYOLA HEIGHTS QC",
      "RE THE O PLACE KAMUNING",
      "RE QUEZON AVENUE",
      "RE FARMERS ARANETA CUBAO",
      "RE MANHATTAN HEIGHTS CUBAO",
      "RE MAGINHAWA TEACHERS VILLAGE",
      "RE P TUAZON BENITEZ QC",
      "RE N DOMINGO SAN JUAN",
      "RE LIBERTY BUILDING BONI",
      "RE ARNAIZ PASAY",
      "RE METRO POINT MALL TAFT",
      "RE 100 WEST MAKATI",
      "RE SAN LORENZO PLACE MAKATI",
      "RE AURORA ESCALADES CUBAO",
      "RE UP SHOPPING CENTER",
      "RE PROJECT 4 QUEZON CITY",
      "RE CITYLAND SANTOLAN PASIG",
      "RE THE LINK METRO EAST PASIG",
      "RE JOCEVIL CENTRE TUMANA",
      "RE C&B CIRCLE MALL MARIKINA",
      "RE SAN MATEO",
      "RE KAMBAL ROAD SAN MATEO RIZAL",
      "RE HILLSIDE PLAZA SUMULONG",
      "RE BIRMINGHAM MEADOWS RIZAL",
      "RE PLATINUM PLAZA PARDO CEBU",
      "RE BASAK LAPU-LAPU CEBU",
      "RE CABAHUG CEBU",
      "RE MACTAN NEWTOWN CENTER",
      "RE GUN-OB LOOC CEBU",
      "RE PAJAC LAPU-LAPU CITY",
      "RE VIBO PLACE CEBU",
      "RE KINGSVILLE ANTIPOLO"
    ],

    "Shopwise": [
      "SHOPWISE COMMONWEALTH",
      "SHOPWISE SAN ROQUE ANTIPOLO",
      "SHOPWISE CIRCUIT MAKATI",
      "SHOPWISE THE SHOPKING SAN FERNANDO",
      "CHINO ROCOES",
      "SHOPWISE GATEWAY MALL 2",
      "SHOPWISE FESTIVAL MALL ALABANG",
      "SHOPWISE GRAND TERMINAL BATANGAS",
      "SHOPWISE IMUS",
      "SHOPWISE LANCASTER IMUS",
      "SHOPWISE SAN PEDRO LAGUNA",
      "SHOPWISE STA ROSA",
      "SHOPWISE SUCAT",
      "SHOPWISE OLIVAREZ",
      "SHOPWISE BASAK CEBU"
    ],

    "The Marketplace": [
      "TMP EASTWOOD LIBIS",
      "TMP LEONARD WOOD BAGUIO",
      "TMP SANTOLAN TOWN PLAZA",
      "TMP CORINTHIAN HILLS",
      "TMP KATIPUNAN",
      "TMP MILLE LUCE VC RIZAL",
      "TMP MPC SAN JUAN (P GUEVARRA)",
      "TMP EDSA SHANGRI LA",
      "TMP TOMAS MORATO",
      "TMP MAGNOLIA",
      "TMP OPUS BRIDGETOWNE",
      "TMP CAPITOL HILLS",
      "TMP MET LIVE PASAY",
      "TMP POWERPLANT MALL ROCKWELL",
      "TMP THE GROVE PASIG",
      "TMP 8 FORBES TOWN ROAD TAGUIG",
      "TMP MAKATI",
      "TMP VENICE GRAND MCKINLEY"
    ],
    
    "Uncle Johns": [
      "UJ PEACOCK PLAZA",
      "UJ NICE HOTEL",
      "UJ VERTIS NORTH",
      "UJ NORTH RESIDENCES",
      "UJ KAINGIN",
      "UJ ONE JOROMA PLACE",
      "UJ IGNACIA PLACE",
      "UJ VICTORIA STATION",
      "UJ NORTH EDSA",
      "FC DILIMAN",
      "FC SUGARTOWNE",
      "UJ STANFORD",
      "UJ ESCALADES EAST TOWER",
      "UJ AMAIA CUBAO",
      "UJ CAPITAL TOWER",
      "UJ E RODRIGUEZ",
      "UJ NEW YORK",
      "UJ DELOS SANTOS",
      "UJ ROBINSONS MAGNOLIA",
      "UJ GILMORE",
      "UJ F CASTILLO",
      "UJ ANONAS",
      "UJ PHILCOA",
      "FC UP TECHNO HUB",
      "UJ LE GRAND 2",
      "UJ CYBERMALL",
      "UJ ACROPOLIS",
      "UJ ETON CYBERPOD",
      "UJ GALLERIA",
      "UJ ROBINSONS GALLERIA KIOSK",
      "UJ BRIDGETOWNE",
      "UJ SHELL C5 BAGUMBAYAN",
      "UJ SHELL KATIPUNAN",
      "UJ STUDIO A",
      "UJ XAVIERVILLE",
      "UJ-LA FAYETTE 1",
      "FC ZETA TOWER",
      "FC TERA TOWER",
      "UJ TOMAS MORATO",
      "UJ SCT DE GUIA",
      "UJ HEART CENTER",
      "UJ ST PETER Q AVE",
      "UJ D TUAZON",
      "UJ MAYON",
      "UJ DOÑA IMELDA",
      "UJ SHOPS@VICTORIA",
      "UJ PANAY",
      "UJ GMA COOP",
      "UJ V LUNA AVE",
      "FC GOLDEN PANDA",
      "UJ REPUBLICAN COLLEGE",
      "UJ 12TH AVE CUBAO",
      "UJ BONI SERRANO",
      "UJ GA TOWER",
      "UJ VRP CARPARK",
      "UJ CITYNET CENTRAL",
      "UJ SIERRA MADRE 2",
      "UJ CALIFORNIA GARDEN",
      "UJ G SQUARE",
      "UJ S SQUARE",
      "UJ JP RIZAL MANDALUYONG",
      "UJ MADISON SQR N DOMINGO",
      "UJ P GUEVARRA",
      "UJ ARCEL",
      "UJ ANNAPOLIS",
      "UJ CONCENTRIX MEGAMALL",
      "UJ MILLENIUM PLACE",
      "UJ SUNSHINE 100",
      "FC CYBERGATE 1",
      "FC CYBERGATE 2",
      "FC CYBERGATE 3",
      "FC CYBERGATE PLAZA",
      "FC GATEWAY REGENCY",
      "UJ DINALUPIHAN PLAZA",
      "UJ OLONGAPO",
      "FC SUBIC WORLD PLAZA",
      "FC FILOIL SUBIC",
      "FC MOONBAY MARINA",
      "FC AMIRES",
      "FC FREEPORT MANSION",
      "FC OLONGAPO 2",
      "FC WOW BUILDING",
      "UJ MARIVELES TOWN PROPER",
      "UJ MARIVELES FAB ANNEX",
      "FC MARIVELES",
      "UJ CLARK 2",
      "UJ PHILEXCEL",
      "UJ CENTER@CLARK",
      "UJ SAN LEONARDO",
      "UJ CABIAO",
      "UJ ROBINSONS LUISITA",
      "UJ CIA BUS PORT",
      "UJ CIA DEPARTURE",
      "FC CALTEX LUISITA",
      "UJ DAU",
      "UJ ABAD SANTOS",
      "UJ ERSON",
      "UJ ROBINSONS ANGELES",
      "UJ MAGALANG PLAZA",
      "UJ ENTEC 2",
      "UJ DISTRICT ANGELES",
      "UJ FIELDS AVENUE",
      "UJ TOTAL DAU",
      "UJ LAMAO",
      "UJ ST JOSEPH BALANGA",
      "UJ GUAGUA",
      "UJ STARMILLS",
      "UJ STARMILLS TERMINAL",
      "UJ SINDALAN",
      "UJ PILAR",
      "UJ ORION",
      "FC PILAR MUNICIPAL HALL",
      "UJ HAGONOY",
      "UJ BALIUAG",
      "UJ TABANG",
      "UJ SAN JOSE POBLACION",
      "UJ ANGAT PLAZA",
      "UJ MDH",
      "UJ BOCAUE 2",
      "UJ TIKAY",
      "UJ TOWNVILLE PULILAN",
      "FC SAN RAFAEL PM",
      "FC PAOMBONG",
      "FC CABANAS MALOLOS",
      "FC MANLY TOWN CENTER",
      "UJ ZABARTE",
      "UJ PTT NOVA",
      "UJ OLD SAUYO",
      "UJ ROBINSONS NOVA",
      "UJ GREENFIELDS SUBD",
      "UJ FEU-NRMF",
      "UJ GULOD NOVALICHES",
      "UJ BAGONG SILANG PH 10",
      "UJ CAMARIN",
      "FC TEACHERS VILLAGE",
      "UJ FATIMA MAIN",
      "UJ ROBINSONS MALABON",
      "UJ MARULAS",
      "UJ PASO DE BLAS",
      "UJ STA QUITERIA",
      "UJ ARANETA SQUARE",
      "UJ 12TH AVE CALOOCAN",
      "FC TIRONA",
      "UJ SKYLAND",
      "UJ SJG",
      "UJ CONCENTRIX G5",
      "UJ GLORIETTA 2",
      "UJ SANTILLAN",
      "UJ AN EXCHANGE",
      "UJ CHINO ROCES",
      "UJ MAKATI MEDICAL RELOCATION",
      "UJ LA FUERZA",
      "UJ THE COLUMNS",
      "UJ MAKATI EXECUTIVE TOWER 1",
      "UJ YAKAL",
      "UJ PMI TOWER",
      "FC THE LINEAR TOWER",
      "FC PASONG TAMO",
      "FC DBP",
      "UJ CITYLAND HERRERA",
      "UJ FOUR SEASONS",
      "UJ CLASSICA TOWER II",
      "UJ ELIZABETH PLACE",
      "UJ COSMOPOLITAN",
      "UJ VERNIDA IV",
      "UJ GUADALUPE NUEVO",
      "UJ ANTEL 2000 TOWER",
      "UJ LIBERTY",
      "UJ CYPRESS GARDEN",
      "UJ BENAVIDEZ",
      "UJ BLOOMINGDALE",
      "UJ CATTLEYA",
      "UJ WINDSOR",
      "UJ VALERO",
      "FC ROBINSONS SUMMIT CENTER",
      "UJ GIL FERNANDO",
      "UJ FREEDOM PARK",
      "UJ PTT MARIKINA",
      "UJ SHELL MOLAVE",
      "UJ XELAND",
      "UJ STO NIÑO",
      "UJ METRO EAST KIOSK",
      "UJ CANIOGAN",
      "UJ COUNTRYSIDE",
      "UJ MANGGAHAN",
      "UJ MERCEDES TOWN CENTER",
      "FC SHELL JP RIZAL MARIKINA",
      "UJ MALAYAN PLAZA",
      "UJ HANSTON",
      "UJ EAST OF GALLERIA",
      "UJ CYBERSCAPE ALPHA",
      "UJ CYBERSCAPE BETA",
      "UJ RET",
      "UJ PARC CHATEAU",
      "UJ SHELL EMERALD AVENUE",
      "UJ MONTOJO",
      "UJ CUBE",
      "UJ ESGUERA",
      "UJ AMPERE",
      "FC ONE SAN MIGUEL",
      "UJ H JAVIER",
      "UJ PASIG BLVD",
      "UJ PIONEER CENTER",
      "UJ TRANSCOM",
      "UJ CYBER OMEGA",
      "UJ ESCRIVA",
      "UJ ORTIGAS TECHNOPOINT",
      "UJ PEARL DRIVE",
      "UJ THE MEDICAL CITY KIOSK",
      "UJ EXCHANGE REGENCY",
      "UJ ROCKWELL",
      "UJ PEDRO GIL",
      "UJ VIZCARRA",
      "UJ BOCOBO",
      "UJ REMEDIOS CIRCLE",
      "UJ HOTEL SORIENTE",
      "UJ EGI TAFT",
      "UJ LEGASPI TOWER",
      "UJ ROBINSONS PLACE MANILA",
      "UJ BURGUNDY",
      "FC THREE ADRIATICO",
      "FC MAGSAYSAY",
      "UJ ST THOMAS SQUARE",
      "UJ F CAYCO",
      "UJ P NOVAL",
      "UJ LEGARDA WILSON",
      "UJ DAPITAN 2",
      "UJ VG CRUZ",
      "UJ MATIMYAS",
      "UJ IBARRA",
      "UJ RECTO",
      "UJ R HIDALGO 2",
      "FC SANTOL",
      "UJ DANGWA",
      "UJ AURORA",
      "UJ R PAPA MANILA",
      "UJ TAYUMAN",
      "UJ MAYHALIGUE",
      "UJ PLAZA LACSON",
      "UJ ESCOLTA",
      "UJ MACARAIG",
      "UJ INTRAMUROS 2",
      "FC INTRAMUROS 1",
      "FC INTRAMUROS 3",
      "UJ ASTRAL TOWER",
      "UJ APACIBLE",
      "UJ UNLAD",
      "UJ REMEDIOS",
      "UJ ARELLANO",
      "UJ LOURDES",
      "UJ ST SCHOLASTICA",
      "UJ FELIX STA ANA",
      "UJ MALACAÑANG",
      "UJ ZEN TOWER",
      "UJ G&H BUILDING TEJERON",
      "UJ OSMAK",
      "UJ BLUE SAPPHIRE",
      "UJ AVIDA CITYFLEX",
      "UJ CYBERSIGMA",
      "UJ FORBESWOOD",
      "UJ TRION TOWER 3",
      "UJ W CITY CENTER",
      "UJ MARKET MARKET2",
      "FC SIGNAL VILLAGE",
      "FC INOZA",
      "FC BOTT",
      "UJ CB MALL",
      "UJ HAVILA",
      "UJ SAN ROQUE ANTIPOLO",
      "UJ ROBINSONS CAINTA",
      "UJ RIVERSIDE",
      "UJ MONTALBAN",
      "UJ CAINTA GREENPARK",
      "UJ F MANALO SUMULONG",
      "UJ VILLAGE EAST",
      "UJ VALLEY GOLF",
      "UJ BROOKSIDE",
      "UJ TRES PALMAS",
      "UJ WESTERN BICUTAN",
      "UJ MRT AVE",
      "UJ MANILA EAST",
      "UJ MORONG",
      "UJ RUBLOU",
      "UJ TAYTAY",
      "UJ RUBLOU CAMBRIDGE",
      "UJ DOLORES TAYTAY",
      "FC GREENWOODS 2",
      "UJ MALIBAY",
      "UJ EASTFIELD",
      "UJ FB HARRISON",
      "UJ 2470 DOMINGA DORMITORY",
      "UJ DOMINGA",
      "UJ ROXAS BLVD",
      "UJ CEBU PACIFIC",
      "UJ SEA RESIDENCES",
      "UJ DOUBLE DRAGON",
      "UJ MERVILLE",
      "UJ LA HUERTA",
      "UJ NAIA ROAD",
      "UJ RI-RANCE",
      "UJ AYALA MALL BAY AREA",
      "UJ ASEANA 2",
      "UJ BACLARAN",
      "UJ BAYVIEW",
      "UJ 8912 ASEANA",
      "UJ ARISTA PLACE",
      "UJ PITX",
      "FC SOLAIRE",
      "FC SOLAIRE NORTH",
      "UJ SAN ANTONIO",
      "UJ SILVERIO COMPOUND",
      "UJ EL GRANDE",
      "UJ FOUNTAIN BREEZE",
      "UJ FOURTH ESTATE",
      "UJ DELA RAMA",
      "UJ CHATEAU ELYSEE",
      "UJ DON BOSCO",
      "UJ ARMSTRONG",
      "UJ SUN VALLEY",
      "UJ MULTICELIA",
      "FC MULTINATIONAL",
      "UJ BAYANAN",
      "UJ CONVERGYS ALABANG 3",
      "UJ PILAR VILLAGE",
      "UJ ALMANZA UNO",
      "UJ TALON UNO",
      "UJ GOLDEN GATE",
      "UJ LITTLE MARKET",
      "UJ JOSE ABELLO",
      "UJ GLORIA DIAZ",
      "UJ CAA ROAD",
      "UJ VERGONVILLE",
      "UJ BF RESORT",
      "UJ SHELL TUNASAN",
      "FC CIVIC PLACE",
      "UJ EPSON",
      "UJ LIPA CATHEDRAL",
      "UJ ROBINSONS LIPA",
      "UJ TAMBO LIPA",
      "UJ SUMMER HILLS",
      "UJ BATANGAS CITY",
      "UJ UB MAIN CAMPUS",
      "UJ LEMERY",
      "UJ LIFESTYLE STRIP",
      "FC ALANGILAN",
      "UJ TECH TOWER",
      "UJ ESCARIO",
      "UJ BANILAD",
      "UJ ST PETER IMUS CEBU",
      "UJ GALLERIA RESIDENCES CEBU",
      "UJ CYBERGATE GALLERIA CEBU",
      "UJ ONE TREE PLAZA HOTEL",
      "UJ LIGHT FUELS CEBU",
      "FC PARKMALL",
      "UJ STAROIL MASLOG",
      "FC SILLIMAN MED UNIVERSITY",
      "UJ ADDAS GREENFIELDS",
      "UJ LUMINA POINT",
      "UJ IMUS PLAZA",
      "UJ PALICO",
      "UJ RECOLETOS",
      "UJ MAGDIWANG HIGHWAY",
      "UJ DIAMOND IMUS",
      "UJ ALAPAN",
      "UJ MEDICION",
      "UJ WOOD ESTATE",
      "UJ JUSTINVILLE",
      "UJ PANAPAAN",
      "UJ BACOOR POBLACION",
      "UJ SHELL SALITRAN",
      "UJ LA SALLE DASMA 2",
      "UJ BANABA",
      "UJ SALAWAG",
      "UJ CENTURY PALIPARAN",
      "UJ HOPE",
      "UJ FAITH",
      "UJ ROBINSONS PLACE DASMA",
      "UJ FCIE",
      "UJ SUNNY BROOKE",
      "UJ TRECE MARTIREZ",
      "UJ LAVER TANZA",
      "UJ MENDEZ",
      "UJ MENDEZ TAGAYTAY",
      "UJ TAGAYTAY ROTONDA",
      "UJ MALITLIT",
      "UJ DON JOSE STA ROSA",
      "UJ UNITED BAYANIHAN",
      "UJ EL VINDA",
      "UJ MA AURORA",
      "UJ CARILLO",
      "UJ PACITA",
      "UJ SOUTHWOODS",
      "UJ GALLERIA SOUTH",
      "UJ ROBINSONS STA ROSA",
      "UJ SOUTH CITY",
      "UJ SHELL SLEX",
      "UJ UNO CALAMBA",
      "UJ KAPAYAPAAN VILLAGE",
      "UJ UP LB VEGA",
      "UJ STA CRUZ POBLACION",
      "UJ SAN ISIDRO",
      "UJ BANLIC",
      "UJ LOS BAÑOS JUNCTION",
      "UJ VICTORY MALL STA ROSA",
      "UJ 1D CALAUAN",
      "FC SAINT ROSE",
      "UJ ROBINSONS PLACE NAGA",
      "UJ PLAZA QUEZON",
      "UJ PEÑAFRANCIA",
      "UJ PANGANIBAN",
      "UJ LEGASPI",
      "UJ GUMACA QUEZON",
      "FC LUCENA Q AVE",
      "FC LUCENA Q AVE 2",
      "FC LUCENA Q AVE 3"
    ],

    "No Brand": [
      "NB RP GALLERIA ORTIGAS",
      "NB METROEAST",
      "NB UP TOWN CENTER",
      "NB ANTIPOLO",
      "NB SHANGRI-LA PLAZA",
      "NB MAGNOLIA",
      "NB MANILA BAY",
      "NB IMUS",
      "NB FESTIVAL",
      "NB GLORIETTA 4",
      "NB ALABANG TOWN CENTER",
      "NB ERMITA MANILA",
      "NB AYALA CENTER CEBU",
      "NB CIRCUIT MAKATI"
    ]
  },

  "categories": {
    "Food Safety and Quality": [
      "Expired",
      "Poor Quality",
      "Damaged",
      "Foreign Object",
      "Food Poisoning",
      "Food Illness"
    ],

    "Service / Store Services": [
      "Employee Behavior",
      "Long Queue",
      "Price Discrepancy",
      "Incomplete/Missing/Wrong Items",
      "Official Receipt/Invoice",
      "Parking Issue",
      "Payment Issue",
      "Pay & Go"
    ],

    "Rewards": [
      "Go Rewards Issues",
      "Go Tyme Rewards Points Issues"
    ],

    "Safety": [
      "Slip and Fall Injury",
      "Store Facilities & Equipment"
    ],

    "Store Security": [
      "Property Loss",
      "Customer Behavior",
      "Scam/Fraud",
      "Property Damage"
    ],

    "Career Opportunity": [
      "Applications",
      "Applicant Follow-up"
    ],

    "Proposals": [
      "Marketing & Business Proposals",
      "Other Proposals",
      "New Product Supplier",
      "Site Proposal",
      "Bulk Order Quotation"
    ],

    "Inquiries": [
      "Product Inquiry",
      "Store Contact Number",
      "Wellness Activities",
      "Gift Certificates",
      "Store Leasing Inquiries",
      "Other Retail Brand Inquiry"
    ],

    "Feedback": [
      "Commendations",
      "Comments & Suggestions"
    ],

    "eCommerce": [
      "Grabmart",
      "Metromart",
      "Foodpanda",
      "Pickaroo",
      "Shopee",
      "Lazada",
      "Tiktok"
    ],

    "Discount Issues x Government / Legal Letters": [
      "Senior Citizen",
      "PWD",
      "PEZA/Other Gov't Discounts",
      "Notice from Gov't (DTI/DA/DOH Sanitary)",
      "OR/Manual SI"
    ]
  }};

  const businessUnitSelect = document.getElementById("businessUnit");
  const storeSelect = document.getElementById("store");
  const categorySelect = document.getElementById("category");
  const concernSelect = document.getElementById("concern");

  // Ensure the script runs after the DOM is fully loaded
  document.addEventListener('DOMContentLoaded', function() {
    // Business Unit -> Store dependency
    businessUnitSelect.addEventListener("change", function () {
      const businessUnit = this.value;

      storeSelect.innerHTML = "";
      storeSelect.disabled = true;

      if (!dependencyMap.businessUnits[businessUnit]) {
        storeSelect.innerHTML = '<option value="">--Select Business Unit First--</option>';
        return;
      }

      storeSelect.disabled = false;
      storeSelect.innerHTML = '<option value="">--None--</option>';

      dependencyMap.businessUnits[businessUnit].forEach(store => {
        const option = document.createElement("option");
        option.value = store;
        option.textContent = store;
        storeSelect.appendChild(option);
      });
    });

    // Category -> Concern dependency
    categorySelect.addEventListener("change", function () {
      const category = this.value;

      concernSelect.innerHTML = "";
      concernSelect.disabled = true;

      if (!dependencyMap.categories[category]) {
        concernSelect.innerHTML = '<option value="">--Select Category First--</option>';
        return;
      }

      concernSelect.disabled = false;
      concernSelect.innerHTML = '<option value="">--None--</option>';

      dependencyMap.categories[category].forEach(concern => {
        const option = document.createElement("option");
        option.value = concern;
        option.textContent = concern;
        concernSelect.appendChild(option);
      });
    });
  });
